/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Acceso.Entidad.MasterEmployee;
import Acceso.Entidad.MasterTitle;
import Acceso.Objeto.TableTitles;
import Logica.Objeto.Hiring;
import Resources.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niel
 */
public class Window extends javax.swing.JFrame {

    Hiring hiring = new Hiring();
    DefaultTableModel model;

    /**
     * Creates new form Window
     */
    public Window() {
        model = new DefaultTableModel(new String[]{"Numero", "Fecha de Nacimiento", "Nombres", "Apellidos", "Sexo", "Fecha de Contratacion"}, 0);
        
        initComponents();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        Conexion.Connect();
        populateTable();

    }

    boolean populateTable() {
        try {
            this.model = new DefaultTableModel(new String[]{"Numero", "Fecha de Nacimiento", "Nombres", "Apellidos", "Sexo", "Fecha de Contratacion"}, 0);
            jTable1.setModel(model);
            List<MasterEmployee> lme = hiring.getMasterEmployees();
            //model = new DefaultTableModel(new String[]{"Numero", "Fecha de Nacimiento", "Nombres", "Apellidos", "Sexo", "Fecha de Contratacion"}, 0);
            for (int i = 0; i < lme.size(); i++) {
                MasterEmployee aux = lme.get(i);
                model.addRow(new Object[]{aux.getEmp_no(), aux.getBirth_date(), aux.getFirst_name(), aux.getLast_name(), aux.getGender(), aux.getHire_date()});
                //System.out.println(lme.get(i).toString());
            }
            return true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Eggs are not supposed to be green.",
                    "Inane error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
            //Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            int rowid = Integer.valueOf(model.getValueAt(jTable1.getSelectedRow(), 0).toString()).intValue();
            hiring.deleteEmployee(rowid);
            JOptionPane.showMessageDialog(this,
                    "Empleado numero " + rowid + " eliminado con exito.");
            this.populateTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Ha ocurrido un error al intentar eliminar empleado.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dialog diag = new Dialog(this);
        diag.setVisible(true);
        int row = jTable1.getSelectedRow();
        MasterEmployee meaux = new MasterEmployee(Integer.valueOf(model.getValueAt(row, 0).toString()).intValue(),
                java.sql.Date.valueOf(model.getValueAt(row, 1).toString()),
                model.getValueAt(row, 2).toString(),
                model.getValueAt(row, 3).toString(),
                model.getValueAt(row, 4).toString(),
                java.sql.Date.valueOf(model.getValueAt(row, 5).toString()));
        diag.setEmployee(meaux);
        diag.setAction("add");
        diag.populateFields();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dialog diag = new Dialog(this);
        diag.setVisible(true);
        int row = jTable1.getSelectedRow();
        MasterEmployee meaux = new MasterEmployee(Integer.valueOf(model.getValueAt(row, 0).toString()).intValue(),
                java.sql.Date.valueOf(model.getValueAt(row, 1).toString()),
                model.getValueAt(row, 2).toString(),
                model.getValueAt(row, 3).toString(),
                model.getValueAt(row, 4).toString(),
                java.sql.Date.valueOf(model.getValueAt(row, 5).toString()));
        diag.setEmployee(meaux);
        diag.setAction("upd");
        diag.populateFields();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            try {
                int row = jTable1.getSelectedRow();
                MasterEmployee meaux = new MasterEmployee(Integer.valueOf(model.getValueAt(row, 0).toString()).intValue(),
                        java.sql.Date.valueOf(model.getValueAt(row, 1).toString()),
                        model.getValueAt(row, 2).toString(),
                        model.getValueAt(row, 3).toString(),
                        model.getValueAt(row, 4).toString(),
                        java.sql.Date.valueOf(model.getValueAt(row, 5).toString()));
                
                List<MasterTitle> lmt = hiring.getTitles(meaux.getEmp_no());
                frmTitles ft = new frmTitles(lmt);
                ft.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (evt.getClickCount() == 1) {

        }
    }//GEN-LAST:event_jTable1MouseClicked

    @Override
    public void dispose() {
        try {
            System.out.println("Closed");
            Conexion.Disconnect();
            super.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
